### ISSUE TITLE
public function getPostMetaItems assume WP table handle

### ISSUE THREAD

**Issue by twykr** [integromat/wordpress-rest-api-custom-fields#2]
in `settings/ObjectTypes/PostMeta.php`, lines 150-151, the script currently assumes that the Wordpress install is using the default table prefix of "wp_", rather than properly relying on `$wpdb->prefix` (for the postmeta and posts tables).  The fixed code looks like this:

`        public function getPostMetaItems()
        {
                global $wpdb;
                $query = "
                        SELECT
                                p.post_type,
                                m.meta_key
                        FROM ".$wpdb->prefix."_postmeta m
                        INNER JOIN ".$wpdb->prefix."_posts p ON p.ID = m.post_id
                        ORDER BY 
                                post_type,
                                meta_key                        
                ";
                $meta_keys = $wpdb->get_results($query);
                return $meta_keys;
        }`

**Comment by petrmm** [comment]
Thank you for reporting the problem. We solved it some time ago.
